import { CUSTOMER_TABS, MASTER_TABS } from "@/lib/intelligence/owner-network/constants";

export const MASTER_HEADERS: Record<string, string[]> = {
  [MASTER_TABS.customers]: [
    "workspace_id",
    "workspace_name",
    "workspace_slug",
    "owner_email",
    "customer_sheet_id",
    "customer_sheet_url",
    "status",
    "created_at",
    "updated_at",
  ],
  [MASTER_TABS.projects]: [
    "workspace_id",
    "project_id",
    "project_slug",
    "project_label",
    "mode",
    "status",
    "ga4_property_record_id",
    "ga4_property_id",
    "ga4_property_label",
    "gsc_site_record_id",
    "gsc_site_url",
    "last_synced_at",
    "customer_sheet_id",
  ],
  [MASTER_TABS.syncHealth]: [
    "ran_at",
    "workspace_id",
    "project_id",
    "project_slug",
    "provider",
    "status",
    "rows_synced",
    "message",
    "customer_sheet_id",
  ],
};

export const CUSTOMER_HEADERS: Record<string, string[]> = {
  [CUSTOMER_TABS.projects]: [
    "workspace_id",
    "project_id",
    "project_slug",
    "project_label",
    "mode",
    "status",
    "ga4_property_record_id",
    "ga4_property_id",
    "ga4_property_label",
    "gsc_site_record_id",
    "gsc_site_url",
    "last_synced_at",
  ],
  [CUSTOMER_TABS.syncHealth]: [
    "ran_at",
    "workspace_id",
    "project_id",
    "project_slug",
    "provider",
    "status",
    "rows_synced",
    "message",
  ],
  [CUSTOMER_TABS.ga4SourceDaily]: [
    "workspace_id",
    "project_id",
    "project_slug",
    "project_label",
    "date",
    "source",
    "medium",
    "sessions",
    "users",
    "engaged_sessions",
    "conversions",
    "synced_at",
  ],
  [CUSTOMER_TABS.ga4LandingPageDaily]: [
    "workspace_id",
    "project_id",
    "project_slug",
    "project_label",
    "date",
    "landing_page",
    "page_path",
    "sessions",
    "users",
    "engaged_sessions",
    "conversions",
    "synced_at",
  ],
  [CUSTOMER_TABS.gscQueryDaily]: [
    "workspace_id",
    "project_id",
    "project_slug",
    "project_label",
    "date",
    "query",
    "clicks",
    "impressions",
    "ctr",
    "position",
    "synced_at",
  ],
  [CUSTOMER_TABS.gscPageDaily]: [
    "workspace_id",
    "project_id",
    "project_slug",
    "project_label",
    "date",
    "page",
    "clicks",
    "impressions",
    "ctr",
    "position",
    "synced_at",
  ],
};