export const INTELLIGENCE_HEADERS = {
  insightsGenerated: [
    "insight_id",
    "run_key",
    "workspace_id",
    "project_id",
    "project_slug",
    "project_label",
    "analysis_window_from",
    "analysis_window_to",
    "category",
    "severity",
    "hypothesis_rank",
    "priority_score",
    "impact_estimated_clicks",
    "evidence_summary",
    "missing_data_reason",
    "title",
    "finding",
    "rationale",
    "evidence_json",
    "recommended_action",
    "data_sufficiency",
    "missing_data_json",
    "model_provider",
    "model_version",
    "generated_at",
  ],
  recommendations: [
    "recommendation_id",
    "run_key",
    "insight_id",
    "workspace_id",
    "project_id",
    "project_slug",
    "priority",
    "priority_score",
    "impact_estimated_clicks",
    "evidence_summary",
    "title",
    "action",
    "expected_outcome",
    "evidence_json",
    "generated_at",
  ],
} as const;